# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiancousin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
